### ISSUE TITLE
Get .sra files without convertion

### ISSUE THREAD

**Issue by FionaMoon** [wwood/kingfisher-download#18]
Hi,
*Kingfisher* is a wonderful tool for download and it really helps me alot.
I have a question when using this tool : what should I do if I just want .sra files but not fastq ?
I find that *Kingfisher* will convert .sra files into fastq automatically when I use the following code 
```
kingfisher get -r SRR7692286 -m aws-http prefetch -t 16
```
In your tutorial，it mentions that 'the default parameter of *--output-format-possibilities* is fastq, shall I change it to other format?

Thank you inadvance !

**Comment by wwood** [comment]
Thanks for the kind words. Yes just do that and specify sra

Looks like the documentation could do with an update. Will do.

Ben

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: LY ***@***.***>
Sent: Thursday, May 5, 2022 8:06:34 PM
To: wwood/kingfisher-download ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/kingfisher-download] Get .sra files without convertion (Issue #18)


Hi,
Kingfisher is a wonderful tool for download and it really helps me alot.
I have a question when using this tool : what should I do if I just want .sra files but not fastq ?
I find that Kingfisher will convert .sra files into fastq automatically when I use the following code

kingfisher get -r SRR7692286 -m aws-http prefetch -t 16



In your tutorial，it mentions that 'the default parameter of --output-format-possibilities is fastq, shall I change it to other format?

Thank you inadvance !

―
