### ISSUE TITLE
Could you make a bioconda package, please

### ISSUE THREAD

**Issue by SilasK** [wwood/kingfisher-download#20]

**Comment by rpetit3** [comment]
@wwood please feel to ping me when you are ready to toss Kingfisher onto Bioconda. Happy to help with recipe and/or reviews.

Cheers

**Comment by wwood** [comment]
Now there - thanks for patience.

**Comment by wwood** [comment]
Hi @rpetit3 I wonder if you had time to look at a trivial fix for the recepie, in https://github.com/bioconda/bioconda-recipes/pull/38228 please?
