### ISSUE TITLE
Option to set the output directory

### ISSUE THREAD

**Issue by mbhall88** [wwood/kingfisher-download#33]
As the title suggests, it would be great to have an option to designate an output directory rather than using the current directory.

**Comment by wwood** [comment]
I agree - I'll try to find the time, but PRs welcome.

**Comment by mbhall88** [comment]
I went to try and work on adding this but there is a lot of assumptions throughout the code that the files will be in the current working directory. I'll leave it to you to decide how the code could be refactored to make this change easier.

**Comment by wwood** [comment]
Hey,

Yeh - not fun to fix. Luckily today I'm sick so needed something brainless to do. Would you mind testing it out please? There's a bunch of new unit tests but would still benefit from a sanity check from a non-sick-me human.

Thanks.

**Comment by mbhall88** [comment]
Hi @wwood,

Thanks for getting around to this. Sorry to hear you're sick!

I just tested out the tip of master and the option didn't seem to work. 

```
./bin/kingfisher get --output-directory test-out -r ERR3239713 -m ena-ftp
```

it created the output directory okay, but still downloaded the fastqs to the current directory.

**Comment by wwood** [comment]
Ah right, forgot about ENA. Fixed now? For testing you might like to use SRR12118866 instead since it is only 20MB.

**Comment by mbhall88** [comment]
That seems to have fixed my example! Thanks!
