### ISSUE TITLE
 Feature Request: annotate samples using Sample Accession

### ISSUE THREAD

**Issue by nicolo-tellini** [wwood/kingfisher-download#35]
Hi @wwood ,

Wonderful piece of software! 
I am wondering if it is possible `annotate`  also the sample using Sample Accession code. 
Apologize if it is already implemented, I can not find it.  

best

nic

**Comment by wwood** [comment]
Hmm, is this completed? Sounds like a good idea.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________

**Comment by nicolo-tellini** [comment]
Hi @wwood ,

I noticed that this info are already present in the table when I `annotate ` using the run code with the `-a` option.
But yeah, maybe it can be useful using Sample Accession code or having the possibility to partition the info in a way that run code returns info regarding the run and sample code the biological info related to the sample.

best

nic

**Comment by wwood** [comment]
Hi, yes, that's correct. 

I had the impression you meant it would be nice to feed in biosample IDs, rather than get them as output, though. I don't think it can do that, at least not by design.

Thanks for the friendly comments.
