### ISSUE TITLE
[Question] How to download directly to S3 bucket?

### ISSUE THREAD

**Issue by jolespin** [wwood/kingfisher-download#36]
Downloading directly to S3 is much cheaper than downloading to EFS on AWS.  Is there a way to download directly to S3 buckets with `kingfisher get`?

**Comment by wwood** [comment]
Good question. How would that work practically I e. What tool or python library would do that?

**Comment by jolespin** [comment]
`boto3` is the official `aws` `sdk` for Python https://boto3.amazonaws.com/v1/documentation/api/latest/index.html

It might be tricky because I don't think you can gzip and decompress directly on `s3`

**Comment by wwood** [comment]
Hmm, good point. It might be possible by streaming through e.g. a gzip, but you wouldn't be able to use fasterq-dump. Unless you or someone else can think of a path forward here I think it might be in the too hard basket, and so I'll close this issue as wontfix.

But before we get there, can you just mount the s3 and then treat it as a regular folder?

**Comment by jolespin** [comment]
Yea that's what I ended up doing using EFS but the issue ended up being that the bandwidth cost in writing to EFS is astronomical compared to writing to S3.

**Comment by wwood** [comment]
You mounted an S3 bucket through EFS? I think that's a contradiction, no? Maybe I'm not familiar enough.

**Comment by jolespin** [comment]
My (limited) understanding of AWS architecture is that you have an S3 bucket and then you mount it in EFS so you can access it like a normal file system on EC2 but I could be wrong on that. I mostly deal with the downstream analysis instead of setting up the infrastructure. 

When you use the --stdout feature on kingfisher, does this stream the sra -> Fastq > gzip or does it first download the sra and then convert to Fastq sending it to stdout?

**Comment by jolespin** [comment]
I understand the reason for closing.  Thanks for discussing the possibilities with me and answering some questions.  I might work on a wrapper and post it here if it's useful for you.
