### ISSUE TITLE
Method ena-ascp failed

### ISSUE THREAD

**Issue by shandas29** [wwood/kingfisher-download#40]
### 
I'm encountering an issue while trying to use Aspera to download SRA files via Kingfisher get. The command I ran was:
`kingfisher get -p PRJNA504891 -m ena-ascp ena-ftp prefetch`
### 
However, I am consistently getting the following error:

> 09/24/2024 05:44:50 PM INFO: Kingfisher v0.4.1 09/24/2024 05:44:55 PM INFO: Attempting download method ena-ascp for run SRR14018896 .. 09/24/2024 05:44:55 PM INFO: Using aspera ssh key file: /opt/miniconda3/envs/kingfisher/lib/python3.12/site-packages/kingfisher/data/asperaweb_id_dsa.openssh 09/24/2024 05:44:55 PM INFO: Querying ENA for FTP paths for SRR14018896.. 09/24/2024 05:44:56 PM INFO: Downloading 3 FTP read set(s): ftp.sra.ebi.ac.uk/vol1/fastq/SRR140/096/SRR14018896/SRR14018896.fastq.gz, ftp.sra.ebi.ac.uk/vol1/fastq/SRR140/096/SRR14018896/SRR14018896_1.fastq.gz, ftp.sra.ebi.ac.uk/vol1/fastq/SRR140/096/SRR14018896/SRR14018896_2.fastq.gz 09/24/2024 05:44:56 PM INFO: Running command: ascp -T -l 300m -P33001 -k 2 -i /opt/miniconda3/envs/kingfisher/lib/python3.12/site-packages/kingfisher/data/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/SRR140/096/SRR14018896/SRR14018896.fastq.gz . 09/24/2024 05:44:56 PM WARNING: Error downloading from ENA with ASCP: Command ascp -T -l 300m -P33001 -k 2 -i /opt/miniconda3/envs/kingfisher/lib/python3.12/site-packages/kingfisher/data/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/SRR140/096/SRR14018896/SRR14018896.fastq.gz . returned non-zero exit status 1. STDERR was: b'ascp: Cannot resolve target host \nStartup failed, exit\n' STDOUT was: b'' 09/24/2024 05:44:56 PM WARNING: Method ena-ascp failed

### 
However, regular downloads without aspera seems to work fine. 
Any guidance or suggestions on resolving this issue would be greatly appreciated!

**Comment by wwood** [comment]
Hi,

My suspicion is that there is some issue with your ascp install. Has it ever worked?

Downloading that run works fine for me:

```
$ kingfisher get -r SRR14018896 -m ena-ascp

09/25/2024 05:24:15 PM INFO: Kingfisher v0.4.1
09/25/2024 05:24:15 PM INFO: Attempting download method ena-ascp for run SRR14018896 ..
09/25/2024 05:24:15 PM INFO: Using aspera ssh key file: /home/ben/git/kingfisher/kingfisher/data/asperaweb_id_dsa.openssh
09/25/2024 05:24:15 PM INFO: Querying ENA for FTP paths for SRR14018896..
09/25/2024 05:24:16 PM INFO: Downloading 3 FTP read set(s): ftp.sra.ebi.ac.uk/vol1/fastq/SRR140/096/SRR14018896/SRR14018896.fastq.gz, ftp.sra.ebi.ac.uk/vol1/fastq/SRR140/096/SRR14018896/SRR14018896_1.fastq.gz, ftp.sra.ebi.ac.uk/vol1/fastq/SRR140/096/SRR14018896/SRR14018896_2.fastq.gz
09/25/2024 05:24:16 PM INFO: Running command: ascp -T -l 300m -P33001 -k 2 -i /home/ben/git/kingfisher/kingfisher/data/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/SRR140/096/SRR14018896/SRR14018896.fastq.gz .
09/25/2024 05:24:44 PM INFO: Running command: ascp -T -l 300m -P33001 -k 2 -i /home/ben/git/kingfisher/kingfisher/data/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/SRR140/096/SRR14018896/SRR14018896_1.fastq.gz .
```

**Comment by shandas29** [comment]
Hi, 
Thank you for the suggestion. 

I will re-check the installation as aspera has never worked.
