### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by a00101** [wwood/kingfisher-download#9]
I got error below.
How could I do that?
```

python ena-fast-download.py ERR962744
03/12/2021 02:27:29 PM INFO: Using aspera ssh key file: $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh
03/12/2021 02:27:29 PM INFO: Querying ENA for FTP paths for ERR962744..
03/12/2021 02:28:13 PM INFO: Downloading 1 FTP read set(s): ftp.sra.ebi.ac.uk/vol1/fastq/ERR962/ERR962744/ERR962744.fastq.gz
03/12/2021 02:28:13 PM INFO: Running command: ascp -T -l 300m -P33001  -i $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR962/ERR962744/ERR962744.fastq.gz .
ascp: failed to authenticate, exiting.

Session Stop  (Error: failed to authenticate)
Traceback (most recent call last):
  File "ena-fast-download.py", line 115, in <module>
    subprocess.check_call(cmd,shell=True)
  File "/root/anaconda2/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ascp -T -l 300m -P33001  -i $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR962/ERR962744/ERR962744.fastq.gz .' returned non-zero exit status 1

```

**Comment by wwood** [comment]
Hi,

Looks to me like potentially you `$HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh` file doesn't exist? Have you run this tool successfully before?

**Comment by a00101** [comment]
Thanks for your rapid reply.
yes. it worked well before and openssh file exsits.
but it occurred intermittently.

**Comment by wwood** [comment]
Hi,

I just pushed a commit that fixed an issue different to the one you were getting, and now your command seems to work for me. Is there still an issue for you? I'm not sure I can be much help with intermittent issues since they are most likely on the ENA side.

Thanks.

**Comment by a50044758** [comment]
i also meet this problem when i download data form ENA, "ascp: failed to authenticate, exiting. Session Stop  (Error: failed to authenticate)". It was fine before, and this problem suddenly happened in one day. I copy the KEY to my file and used command "ascp -i asperaweb_id_dsa.openssh -l 300M -T -P33001 -k1 era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/SRR500/003/SRR5005053/SRR5005053_1.fastq.gz ."  Can anyone can help me ?

**Comment by a50044758** [comment]
> Hi,
> 
> I just pushed a commit that fixed an issue different to the one you were getting, and now your command seems to work for me. Is there still an issue for you? I'm not sure I can be much help with intermittent issues since they are most likely on the ENA side.
> 
> Thanks.
can you help me fix this problem?  thanks very much!

**Comment by yulchen810** [comment]
Hi,
I want to upload fastq folder to ncbi, I used command **ssh-keygen -f ./private.openssh** to create key, and used command **ascp -i <mypath/to/key_file> -QT -l100m -k1 -d <path/to/folder/containing files> subasp@upload.ncbi.nlm.nih.gov:uploads/***_gmail.com_BcKBPbyC** and get the following error:
Key passphrase: 
ascp: failed to authenticate, exiting.

Session Stop  (Error: failed to authenticate)

at home directory, there is **private.openssh** and **private.openssh.pub** file, there is no ~/.aspera/connect/.. directory. does anyone know what happened?

**Comment by wwood** [comment]
Hi @yulchen810 upload isn't supported by kingfisher, so I won't be able to be much help beyond this comment. From memory though, you will need to get the key from NCBI, not generate it yourself.

**Comment by yulchen810** [comment]
> Hi @yulchen810 upload isn't supported by kingfisher, so I won't be able to be much help beyond this comment. From memory though, you will need to get the key from NCBI, not generate it yourself.

Hi,
I've resolved this problem. Thank you.
